// Kotoba — card data for all three scripts

export const ENGLISH = [
  { letter: 'A', phonetic: '/æ/', word: 'apple',    emoji: '🍎' },
  { letter: 'B', phonetic: '/b/',  word: 'ball',     emoji: '⚽' },
  { letter: 'C', phonetic: '/k/',  word: 'cat',      emoji: '🐱' },
  { letter: 'D', phonetic: '/d/',  word: 'dog',      emoji: '🐶' },
  { letter: 'E', phonetic: '/ɛ/',  word: 'egg',      emoji: '🥚' },
  { letter: 'F', phonetic: '/f/',  word: 'fish',     emoji: '🐟' },
  { letter: 'G', phonetic: '/ɡ/',  word: 'goat',     emoji: '🐐' },
  { letter: 'H', phonetic: '/h/',  word: 'hat',      emoji: '🎩' },
  { letter: 'I', phonetic: '/ɪ/',  word: 'igloo',    emoji: '🏠' },
  { letter: 'J', phonetic: '/dʒ/', word: 'jar',      emoji: '🫙' },
  { letter: 'K', phonetic: '/k/',  word: 'kite',     emoji: '🪁' },
  { letter: 'L', phonetic: '/l/',  word: 'lion',     emoji: '🦁' },
  { letter: 'M', phonetic: '/m/',  word: 'moon',     emoji: '🌙' },
  { letter: 'N', phonetic: '/n/',  word: 'nest',     emoji: '🪺' },
  { letter: 'O', phonetic: '/ɒ/',  word: 'orange',   emoji: '🍊' },
  { letter: 'P', phonetic: '/p/',  word: 'pig',      emoji: '🐷' },
  { letter: 'Q', phonetic: '/kw/', word: 'queen',    emoji: '👑' },
  { letter: 'R', phonetic: '/r/',  word: 'rabbit',   emoji: '🐰' },
  { letter: 'S', phonetic: '/s/',  word: 'sun',      emoji: '☀️' },
  { letter: 'T', phonetic: '/t/',  word: 'tiger',    emoji: '🐯' },
  { letter: 'U', phonetic: '/ʌ/',  word: 'umbrella', emoji: '☂️' },
  { letter: 'V', phonetic: '/v/',  word: 'van',      emoji: '🚐' },
  { letter: 'W', phonetic: '/w/',  word: 'water',    emoji: '💧' },
  { letter: 'X', phonetic: '/ks/', word: 'fox',      emoji: '🦊' },
  { letter: 'Y', phonetic: '/j/',  word: 'yak',      emoji: '🐂' },
  { letter: 'Z', phonetic: '/z/',  word: 'zebra',    emoji: '🦓' },
];

export const SPANISH = [
  { letter: 'A', phonetic: '/a/',  word: 'árbol',    emoji: '🌳' },
  { letter: 'B', phonetic: '/b/',  word: 'boca',     emoji: '👄' },
  { letter: 'C', phonetic: '/k/',  word: 'casa',     emoji: '🏠' },
  { letter: 'D', phonetic: '/d/',  word: 'dedo',     emoji: '👆' },
  { letter: 'E', phonetic: '/e/',  word: 'estrella', emoji: '⭐' },
  { letter: 'F', phonetic: '/f/',  word: 'foca',     emoji: '🦭' },
  { letter: 'G', phonetic: '/ɡ/',  word: 'gato',     emoji: '🐱' },
  { letter: 'H', phonetic: 'silent', word: 'hoja',   emoji: '🍃' },
  { letter: 'I', phonetic: '/i/',  word: 'isla',     emoji: '🏝️' },
  { letter: 'J', phonetic: '/x/',  word: 'jabón',    emoji: '🧼' },
  { letter: 'K', phonetic: '/k/',  word: 'koala',    emoji: '🐨' },
  { letter: 'L', phonetic: '/l/',  word: 'luna',     emoji: '🌙' },
  { letter: 'M', phonetic: '/m/',  word: 'mano',     emoji: '✋' },
  { letter: 'N', phonetic: '/n/',  word: 'nube',     emoji: '☁️' },
  { letter: 'Ñ', phonetic: '/ɲ/',  word: 'niño',     emoji: '👦' },
  { letter: 'O', phonetic: '/o/',  word: 'oso',      emoji: '🐻' },
  { letter: 'P', phonetic: '/p/',  word: 'pato',     emoji: '🦆' },
  { letter: 'Q', phonetic: '/k/',  word: 'queso',    emoji: '🧀' },
  { letter: 'R', phonetic: '/r/',  word: 'rosa',     emoji: '🌹' },
  { letter: 'S', phonetic: '/s/',  word: 'sol',      emoji: '☀️' },
  { letter: 'T', phonetic: '/t/',  word: 'tren',     emoji: '🚂' },
  { letter: 'U', phonetic: '/u/',  word: 'uva',      emoji: '🍇' },
  { letter: 'V', phonetic: '/b/',  word: 'vaca',     emoji: '🐄' },
  { letter: 'W', phonetic: '/w/',  word: 'wifi',     emoji: '📶' },
  { letter: 'X', phonetic: '/ks/', word: 'xilófono', emoji: '🎵' },
  { letter: 'Y', phonetic: '/ʝ/',  word: 'yema',     emoji: '🥚' },
  { letter: 'Z', phonetic: '/θ/',  word: 'zapato',   emoji: '👟' },
];

export const HIRAGANA = [
  { letter: 'あ', romaji: 'a',   phonetic: '/a/',   word: 'あめ',       wordRomaji: 'ame',       emoji: '🍬' },
  { letter: 'い', romaji: 'i',   phonetic: '/i/',   word: 'いぬ',       wordRomaji: 'inu',       emoji: '🐶' },
  { letter: 'う', romaji: 'u',   phonetic: '/ɯ/',   word: 'うみ',       wordRomaji: 'umi',       emoji: '🌊' },
  { letter: 'え', romaji: 'e',   phonetic: '/e/',   word: 'えんぴつ',   wordRomaji: 'enpitsu',   emoji: '✏️' },
  { letter: 'お', romaji: 'o',   phonetic: '/o/',   word: 'おに',       wordRomaji: 'oni',       emoji: '👹' },
  { letter: 'か', romaji: 'ka',  phonetic: '/ka/',  word: 'かさ',       wordRomaji: 'kasa',      emoji: '☂️' },
  { letter: 'き', romaji: 'ki',  phonetic: '/ki/',  word: 'きつね',     wordRomaji: 'kitsune',   emoji: '🦊' },
  { letter: 'く', romaji: 'ku',  phonetic: '/ku/',  word: 'くも',       wordRomaji: 'kumo',      emoji: '☁️' },
  { letter: 'け', romaji: 'ke',  phonetic: '/ke/',  word: 'けむり',     wordRomaji: 'kemuri',    emoji: '💨' },
  { letter: 'こ', romaji: 'ko',  phonetic: '/ko/',  word: 'こま',       wordRomaji: 'koma',      emoji: '🌀' },
  { letter: 'さ', romaji: 'sa',  phonetic: '/sa/',  word: 'さかな',     wordRomaji: 'sakana',    emoji: '🐟' },
  { letter: 'し', romaji: 'shi', phonetic: '/ɕi/',  word: 'しか',       wordRomaji: 'shika',     emoji: '🦌' },
  { letter: 'す', romaji: 'su',  phonetic: '/sɯ/',  word: 'すいか',     wordRomaji: 'suika',     emoji: '🍉' },
  { letter: 'せ', romaji: 'se',  phonetic: '/se/',  word: 'せみ',       wordRomaji: 'semi',      emoji: '🦗' },
  { letter: 'そ', romaji: 'so',  phonetic: '/so/',  word: 'そら',       wordRomaji: 'sora',      emoji: '🌤️' },
  { letter: 'た', romaji: 'ta',  phonetic: '/ta/',  word: 'たこ',       wordRomaji: 'tako',      emoji: '🐙' },
  { letter: 'ち', romaji: 'chi', phonetic: '/tɕi/', word: 'ちょうちょ', wordRomaji: 'chōcho',    emoji: '🦋' },
  { letter: 'つ', romaji: 'tsu', phonetic: '/tsɯ/', word: 'つき',       wordRomaji: 'tsuki',     emoji: '🌙' },
  { letter: 'て', romaji: 'te',  phonetic: '/te/',  word: 'てぶくろ',   wordRomaji: 'tebukuro',  emoji: '🧤' },
  { letter: 'と', romaji: 'to',  phonetic: '/to/',  word: 'とり',       wordRomaji: 'tori',      emoji: '🐦' },
  { letter: 'な', romaji: 'na',  phonetic: '/na/',  word: 'なし',       wordRomaji: 'nashi',     emoji: '🍐' },
  { letter: 'に', romaji: 'ni',  phonetic: '/ni/',  word: 'にじ',       wordRomaji: 'niji',      emoji: '🌈' },
  { letter: 'ぬ', romaji: 'nu',  phonetic: '/nɯ/',  word: 'ぬの',       wordRomaji: 'nuno',      emoji: '🧵' },
  { letter: 'ね', romaji: 'ne',  phonetic: '/ne/',  word: 'ねこ',       wordRomaji: 'neko',      emoji: '🐱' },
  { letter: 'の', romaji: 'no',  phonetic: '/no/',  word: 'のり',       wordRomaji: 'nori',      emoji: '🟫' },
  { letter: 'は', romaji: 'ha',  phonetic: '/ha/',  word: 'はな',       wordRomaji: 'hana',      emoji: '🌸' },
  { letter: 'ひ', romaji: 'hi',  phonetic: '/çi/',  word: 'ひつじ',     wordRomaji: 'hitsuji',   emoji: '🐑' },
  { letter: 'ふ', romaji: 'fu',  phonetic: '/ɸɯ/',  word: 'ふね',       wordRomaji: 'fune',      emoji: '⛵' },
  { letter: 'へ', romaji: 'he',  phonetic: '/he/',  word: 'へび',       wordRomaji: 'hebi',      emoji: '🐍' },
  { letter: 'ほ', romaji: 'ho',  phonetic: '/ho/',  word: 'ほし',       wordRomaji: 'hoshi',     emoji: '⭐' },
  { letter: 'ま', romaji: 'ma',  phonetic: '/ma/',  word: 'まめ',       wordRomaji: 'mame',      emoji: '🫘' },
  { letter: 'み', romaji: 'mi',  phonetic: '/mi/',  word: 'みかん',     wordRomaji: 'mikan',     emoji: '🍊' },
  { letter: 'む', romaji: 'mu',  phonetic: '/mɯ/',  word: 'むし',       wordRomaji: 'mushi',     emoji: '🐛' },
  { letter: 'め', romaji: 'me',  phonetic: '/me/',  word: 'めだか',     wordRomaji: 'medaka',    emoji: '🐠' },
  { letter: 'も', romaji: 'mo',  phonetic: '/mo/',  word: 'もも',       wordRomaji: 'momo',      emoji: '🍑' },
  { letter: 'や', romaji: 'ya',  phonetic: '/ja/',  word: 'やま',       wordRomaji: 'yama',      emoji: '🗻' },
  { letter: 'ゆ', romaji: 'yu',  phonetic: '/jɯ/',  word: 'ゆき',       wordRomaji: 'yuki',      emoji: '❄️' },
  { letter: 'よ', romaji: 'yo',  phonetic: '/jo/',  word: 'よる',       wordRomaji: 'yoru',      emoji: '🌃' },
  { letter: 'ら', romaji: 'ra',  phonetic: '/ra/',  word: 'らいおん',   wordRomaji: 'raion',     emoji: '🦁' },
  { letter: 'り', romaji: 'ri',  phonetic: '/ri/',  word: 'りんご',     wordRomaji: 'ringo',     emoji: '🍎' },
  { letter: 'る', romaji: 'ru',  phonetic: '/rɯ/',  word: 'るびー',     wordRomaji: 'rubī',      emoji: '💎' },
  { letter: 'れ', romaji: 're',  phonetic: '/re/',  word: 'れいぞうこ', wordRomaji: 'reizōko',   emoji: '🧊' },
  { letter: 'ろ', romaji: 'ro',  phonetic: '/ro/',  word: 'ろうそく',   wordRomaji: 'rōsoku',    emoji: '🕯️' },
  { letter: 'わ', romaji: 'wa',  phonetic: '/wa/',  word: 'わに',       wordRomaji: 'wani',      emoji: '🐊' },
  { letter: 'を', romaji: 'wo',  phonetic: '/o/',   word: '(particle)', wordRomaji: '',          emoji: '—' },
  { letter: 'ん', romaji: 'n',   phonetic: '/n/',   word: '(mid-word)', wordRomaji: '',          emoji: '—' },
];

export const KATAKANA = [
  { letter: 'ア', romaji: 'a',   phonetic: '/a/',   word: 'アイス',         wordRomaji: 'aisu',       emoji: '🍦' },
  { letter: 'イ', romaji: 'i',   phonetic: '/i/',   word: 'イルカ',         wordRomaji: 'iruka',      emoji: '🐬' },
  { letter: 'ウ', romaji: 'u',   phonetic: '/ɯ/',   word: 'ウサギ',         wordRomaji: 'usagi',      emoji: '🐰' },
  { letter: 'エ', romaji: 'e',   phonetic: '/e/',   word: 'エビ',           wordRomaji: 'ebi',        emoji: '🦐' },
  { letter: 'オ', romaji: 'o',   phonetic: '/o/',   word: 'オレンジ',       wordRomaji: 'orenji',     emoji: '🍊' },
  { letter: 'カ', romaji: 'ka',  phonetic: '/ka/',  word: 'カメラ',         wordRomaji: 'kamera',     emoji: '📷' },
  { letter: 'キ', romaji: 'ki',  phonetic: '/ki/',  word: 'キリン',         wordRomaji: 'kirin',      emoji: '🦒' },
  { letter: 'ク', romaji: 'ku',  phonetic: '/ku/',  word: 'クマ',           wordRomaji: 'kuma',       emoji: '🐻' },
  { letter: 'ケ', romaji: 'ke',  phonetic: '/ke/',  word: 'ケーキ',         wordRomaji: 'kēki',       emoji: '🎂' },
  { letter: 'コ', romaji: 'ko',  phonetic: '/ko/',  word: 'コアラ',         wordRomaji: 'koara',      emoji: '🐨' },
  { letter: 'サ', romaji: 'sa',  phonetic: '/sa/',  word: 'サメ',           wordRomaji: 'same',       emoji: '🦈' },
  { letter: 'シ', romaji: 'shi', phonetic: '/ɕi/',  word: 'シマウマ',       wordRomaji: 'shimauma',   emoji: '🦓' },
  { letter: 'ス', romaji: 'su',  phonetic: '/sɯ/',  word: 'スイカ',         wordRomaji: 'suika',      emoji: '🍉' },
  { letter: 'セ', romaji: 'se',  phonetic: '/se/',  word: 'セーター',       wordRomaji: 'sētā',       emoji: '🧥' },
  { letter: 'ソ', romaji: 'so',  phonetic: '/so/',  word: 'ソファ',         wordRomaji: 'sofa',       emoji: '🛋️' },
  { letter: 'タ', romaji: 'ta',  phonetic: '/ta/',  word: 'タコ',           wordRomaji: 'tako',       emoji: '🐙' },
  { letter: 'チ', romaji: 'chi', phonetic: '/tɕi/', word: 'チーズ',         wordRomaji: 'chīzu',      emoji: '🧀' },
  { letter: 'ツ', romaji: 'tsu', phonetic: '/tsɯ/', word: 'ツバメ',         wordRomaji: 'tsubame',    emoji: '🐦' },
  { letter: 'テ', romaji: 'te',  phonetic: '/te/',  word: 'テレビ',         wordRomaji: 'terebi',     emoji: '📺' },
  { letter: 'ト', romaji: 'to',  phonetic: '/to/',  word: 'トマト',         wordRomaji: 'tomato',     emoji: '🍅' },
  { letter: 'ナ', romaji: 'na',  phonetic: '/na/',  word: 'ナス',           wordRomaji: 'nasu',       emoji: '🍆' },
  { letter: 'ニ', romaji: 'ni',  phonetic: '/ni/',  word: 'ニワトリ',       wordRomaji: 'niwatori',   emoji: '🐔' },
  { letter: 'ヌ', romaji: 'nu',  phonetic: '/nɯ/',  word: 'ヌードル',       wordRomaji: 'nūdoru',     emoji: '🍜' },
  { letter: 'ネ', romaji: 'ne',  phonetic: '/ne/',  word: 'ネコ',           wordRomaji: 'neko',       emoji: '🐱' },
  { letter: 'ノ', romaji: 'no',  phonetic: '/no/',  word: 'ノート',         wordRomaji: 'nōto',       emoji: '📓' },
  { letter: 'ハ', romaji: 'ha',  phonetic: '/ha/',  word: 'ハト',           wordRomaji: 'hato',       emoji: '🕊️' },
  { letter: 'ヒ', romaji: 'hi',  phonetic: '/çi/',  word: 'ヒツジ',         wordRomaji: 'hitsuji',    emoji: '🐑' },
  { letter: 'フ', romaji: 'fu',  phonetic: '/ɸɯ/',  word: 'フラミンゴ',     wordRomaji: 'furamingo',  emoji: '🦩' },
  { letter: 'ヘ', romaji: 'he',  phonetic: '/he/',  word: 'ヘリコプター',   wordRomaji: 'herikoputā', emoji: '🚁' },
  { letter: 'ホ', romaji: 'ho',  phonetic: '/ho/',  word: 'ホタル',         wordRomaji: 'hotaru',     emoji: '✨' },
  { letter: 'マ', romaji: 'ma',  phonetic: '/ma/',  word: 'マンゴー',       wordRomaji: 'mangō',      emoji: '🥭' },
  { letter: 'ミ', romaji: 'mi',  phonetic: '/mi/',  word: 'ミツバチ',       wordRomaji: 'mitsubachi', emoji: '🐝' },
  { letter: 'ム', romaji: 'mu',  phonetic: '/mɯ/',  word: 'ムース',         wordRomaji: 'mūsu',       emoji: '🫎' },
  { letter: 'メ', romaji: 'me',  phonetic: '/me/',  word: 'メロン',         wordRomaji: 'meron',      emoji: '🍈' },
  { letter: 'モ', romaji: 'mo',  phonetic: '/mo/',  word: 'モモ',           wordRomaji: 'momo',       emoji: '🍑' },
  { letter: 'ヤ', romaji: 'ya',  phonetic: '/ja/',  word: 'ヤギ',           wordRomaji: 'yagi',       emoji: '🐐' },
  { letter: 'ユ', romaji: 'yu',  phonetic: '/jɯ/',  word: 'ユニコーン',     wordRomaji: 'yunikōn',    emoji: '🦄' },
  { letter: 'ヨ', romaji: 'yo',  phonetic: '/jo/',  word: 'ヨット',         wordRomaji: 'yotto',      emoji: '⛵' },
  { letter: 'ラ', romaji: 'ra',  phonetic: '/ra/',  word: 'ライオン',       wordRomaji: 'raion',      emoji: '🦁' },
  { letter: 'リ', romaji: 'ri',  phonetic: '/ri/',  word: 'リンゴ',         wordRomaji: 'ringo',      emoji: '🍎' },
  { letter: 'ル', romaji: 'ru',  phonetic: '/rɯ/',  word: 'ルビー',         wordRomaji: 'rubī',       emoji: '💎' },
  { letter: 'レ', romaji: 're',  phonetic: '/re/',  word: 'レモン',         wordRomaji: 'remon',      emoji: '🍋' },
  { letter: 'ロ', romaji: 'ro',  phonetic: '/ro/',  word: 'ロボット',       wordRomaji: 'robotto',    emoji: '🤖' },
  { letter: 'ワ', romaji: 'wa',  phonetic: '/wa/',  word: 'ワニ',           wordRomaji: 'wani',       emoji: '🐊' },
  { letter: 'ヲ', romaji: 'wo',  phonetic: '/o/',   word: '(particle)',     wordRomaji: '',           emoji: '—' },
  { letter: 'ン', romaji: 'n',   phonetic: '/n/',   word: '(mid-word)',     wordRomaji: '',           emoji: '—' },
];

// Language pair definitions
// Each pair specifies two "sides", each with: id, label, color, cards, and how to extract display fields
export const PAIRS = [
  { id: 'en-es', labelA: 'English', labelB: 'Español',  colorA: '#6B8F71', colorB: '#C17B5A', scriptA: 'latin',   scriptB: 'latin',   dataA: ENGLISH,  dataB: SPANISH  },
  { id: 'en-hi', labelA: 'English', labelB: 'ひらがな',  colorA: '#6B8F71', colorB: '#6B6FA8', scriptA: 'latin',   scriptB: 'kana',    dataA: ENGLISH,  dataB: HIRAGANA },
  { id: 'en-ka', labelA: 'English', labelB: 'カタカナ',  colorA: '#6B8F71', colorB: '#6B6FA8', scriptA: 'latin',   scriptB: 'kana',    dataA: ENGLISH,  dataB: KATAKANA },
  { id: 'es-hi', labelA: 'Español', labelB: 'ひらがな',  colorA: '#C17B5A', colorB: '#6B6FA8', scriptA: 'latin',   scriptB: 'kana',    dataA: SPANISH,  dataB: HIRAGANA },
  { id: 'es-ka', labelA: 'Español', labelB: 'カタカナ',  colorA: '#C17B5A', colorB: '#6B6FA8', scriptA: 'latin',   scriptB: 'kana',    dataA: SPANISH,  dataB: KATAKANA },
  { id: 'hi-ka', labelA: 'ひらがな', labelB: 'カタカナ', colorA: '#6B6FA8', colorB: '#6B6FA8', scriptA: 'kana',    scriptB: 'kana',    dataA: HIRAGANA, dataB: KATAKANA },
];
