// Kotoba — card data for all three scripts

export const ENGLISH = [
  { letter: 'A', phonetic: '/æ/',  word: 'apple',    emoji: '🍎', jpWord: 'りんご',       jpRomaji: 'ringo'     },
  { letter: 'B', phonetic: '/b/',  word: 'ball',     emoji: '⚽', jpWord: 'ボール',       jpRomaji: 'bōru'      },
  { letter: 'C', phonetic: '/k/',  word: 'cat',      emoji: '🐱', jpWord: 'ねこ',         jpRomaji: 'neko'      },
  { letter: 'D', phonetic: '/d/',  word: 'dog',      emoji: '🐶', jpWord: 'いぬ',         jpRomaji: 'inu'       },
  { letter: 'E', phonetic: '/ɛ/',  word: 'egg',      emoji: '🥚', jpWord: 'たまご',       jpRomaji: 'tamago'    },
  { letter: 'F', phonetic: '/f/',  word: 'fish',     emoji: '🐟', jpWord: 'さかな',       jpRomaji: 'sakana'    },
  { letter: 'G', phonetic: '/ɡ/',  word: 'goat',     emoji: '🐐', jpWord: 'やぎ',         jpRomaji: 'yagi'      },
  { letter: 'H', phonetic: '/h/',  word: 'hat',      emoji: '🎩', jpWord: 'ぼうし',       jpRomaji: 'bōshi'     },
  { letter: 'I', phonetic: '/ɪ/',  word: 'igloo',    emoji: '🏠', jpWord: 'かまくら',     jpRomaji: 'kamakura'  },
  { letter: 'J', phonetic: '/dʒ/', word: 'jar',      emoji: '🫙', jpWord: 'びん',         jpRomaji: 'bin'       },
  { letter: 'K', phonetic: '/k/',  word: 'kite',     emoji: '🪁', jpWord: 'たこ',         jpRomaji: 'tako'      },
  { letter: 'L', phonetic: '/l/',  word: 'lion',     emoji: '🦁', jpWord: 'ライオン',     jpRomaji: 'raion'     },
  { letter: 'M', phonetic: '/m/',  word: 'moon',     emoji: '🌙', jpWord: 'つき',         jpRomaji: 'tsuki'     },
  { letter: 'N', phonetic: '/n/',  word: 'nest',     emoji: '🪺', jpWord: 'す',           jpRomaji: 'su'        },
  { letter: 'O', phonetic: '/ɒ/',  word: 'orange',   emoji: '🍊', jpWord: 'みかん',       jpRomaji: 'mikan'     },
  { letter: 'P', phonetic: '/p/',  word: 'pig',      emoji: '🐷', jpWord: 'ぶた',         jpRomaji: 'buta'      },
  { letter: 'Q', phonetic: '/kw/', word: 'queen',    emoji: '👑', jpWord: 'じょおう',     jpRomaji: 'joō'       },
  { letter: 'R', phonetic: '/r/',  word: 'rabbit',   emoji: '🐰', jpWord: 'うさぎ',       jpRomaji: 'usagi'     },
  { letter: 'S', phonetic: '/s/',  word: 'sun',      emoji: '☀️', jpWord: 'たいよう',     jpRomaji: 'taiyō'     },
  { letter: 'T', phonetic: '/t/',  word: 'tiger',    emoji: '🐯', jpWord: 'とら',         jpRomaji: 'tora'      },
  { letter: 'U', phonetic: '/ʌ/',  word: 'umbrella', emoji: '☂️', jpWord: 'かさ',         jpRomaji: 'kasa'      },
  { letter: 'V', phonetic: '/v/',  word: 'van',      emoji: '🚐', jpWord: 'バン',         jpRomaji: 'ban'       },
  { letter: 'W', phonetic: '/w/',  word: 'water',    emoji: '💧', jpWord: 'みず',         jpRomaji: 'mizu'      },
  { letter: 'X', phonetic: '/ks/', word: 'fox',      emoji: '🦊', jpWord: 'きつね',       jpRomaji: 'kitsune'   },
  { letter: 'Y', phonetic: '/j/',  word: 'yak',      emoji: '🐂', jpWord: 'うし',         jpRomaji: 'ushi'      },
  { letter: 'Z', phonetic: '/z/',  word: 'zebra',    emoji: '🦓', jpWord: 'しまうま',     jpRomaji: 'shimauma'  },
];

export const SPANISH = [
  { letter: 'A', phonetic: '/a/',    word: 'árbol',    emoji: '🌳', jpWord: 'き',           jpRomaji: 'ki'        },
  { letter: 'B', phonetic: '/b/',    word: 'boca',     emoji: '👄', jpWord: 'くち',         jpRomaji: 'kuchi'     },
  { letter: 'C', phonetic: '/k/',    word: 'casa',     emoji: '🏠', jpWord: 'いえ',         jpRomaji: 'ie'        },
  { letter: 'D', phonetic: '/d/',    word: 'dedo',     emoji: '👆', jpWord: 'ゆび',         jpRomaji: 'yubi'      },
  { letter: 'E', phonetic: '/e/',    word: 'estrella', emoji: '⭐', jpWord: 'ほし',         jpRomaji: 'hoshi'     },
  { letter: 'F', phonetic: '/f/',    word: 'foca',     emoji: '🦭', jpWord: 'あざらし',     jpRomaji: 'azarashi'  },
  { letter: 'G', phonetic: '/ɡ/',    word: 'gato',     emoji: '🐱', jpWord: 'ねこ',         jpRomaji: 'neko'      },
  { letter: 'H', phonetic: 'silent', word: 'hoja',     emoji: '🍃', jpWord: 'は',           jpRomaji: 'ha'        },
  { letter: 'I', phonetic: '/i/',    word: 'isla',     emoji: '🏝️', jpWord: 'しま',         jpRomaji: 'shima'     },
  { letter: 'J', phonetic: '/x/',    word: 'jabón',    emoji: '🧼', jpWord: 'せっけん',     jpRomaji: 'sekken'    },
  { letter: 'K', phonetic: '/k/',    word: 'koala',    emoji: '🐨', jpWord: 'コアラ',       jpRomaji: 'koara'     },
  { letter: 'L', phonetic: '/l/',    word: 'luna',     emoji: '🌙', jpWord: 'つき',         jpRomaji: 'tsuki'     },
  { letter: 'M', phonetic: '/m/',    word: 'mano',     emoji: '✋', jpWord: 'て',           jpRomaji: 'te'        },
  { letter: 'N', phonetic: '/n/',    word: 'nube',     emoji: '☁️', jpWord: 'くも',         jpRomaji: 'kumo'      },
  { letter: 'Ñ', phonetic: '/ɲ/',    word: 'niño',     emoji: '👦', jpWord: 'こども',       jpRomaji: 'kodomo'    },
  { letter: 'O', phonetic: '/o/',    word: 'oso',      emoji: '🐻', jpWord: 'くま',         jpRomaji: 'kuma'      },
  { letter: 'P', phonetic: '/p/',    word: 'pato',     emoji: '🦆', jpWord: 'あひる',       jpRomaji: 'ahiru'     },
  { letter: 'Q', phonetic: '/k/',    word: 'queso',    emoji: '🧀', jpWord: 'チーズ',       jpRomaji: 'chīzu'     },
  { letter: 'R', phonetic: '/r/',    word: 'rosa',     emoji: '🌹', jpWord: 'バラ',         jpRomaji: 'bara'      },
  { letter: 'S', phonetic: '/s/',    word: 'sol',      emoji: '☀️', jpWord: 'たいよう',     jpRomaji: 'taiyō'     },
  { letter: 'T', phonetic: '/t/',    word: 'tren',     emoji: '🚂', jpWord: 'でんしゃ',     jpRomaji: 'densha'    },
  { letter: 'U', phonetic: '/u/',    word: 'uva',      emoji: '🍇', jpWord: 'ぶどう',       jpRomaji: 'budō'      },
  { letter: 'V', phonetic: '/b/',    word: 'vaca',     emoji: '🐄', jpWord: 'うし',         jpRomaji: 'ushi'      },
  { letter: 'W', phonetic: '/w/',    word: 'wifi',     emoji: '📶', jpWord: 'ワイファイ',   jpRomaji: 'waifai'    },
  { letter: 'X', phonetic: '/ks/',   word: 'xilófono', emoji: '🎵', jpWord: 'もっきん',     jpRomaji: 'mokkin'    },
  { letter: 'Y', phonetic: '/ʝ/',    word: 'yema',     emoji: '🥚', jpWord: 'きみ',         jpRomaji: 'kimi'      },
  { letter: 'Z', phonetic: '/θ/',    word: 'zapato',   emoji: '👟', jpWord: 'くつ',         jpRomaji: 'kutsu'     },
];

export const HIRAGANA = [
  { letter: 'あ', romaji: 'a',   phonetic: '/a/',   word: 'あめ',       wordRomaji: 'ame',       emoji: '🍬' },
  { letter: 'い', romaji: 'i',   phonetic: '/i/',   word: 'いぬ',       wordRomaji: 'inu',       emoji: '🐶' },
  { letter: 'う', romaji: 'u',   phonetic: '/ɯ/',   word: 'うみ',       wordRomaji: 'umi',       emoji: '🌊' },
  { letter: 'え', romaji: 'e',   phonetic: '/e/',   word: 'えんぴつ',   wordRomaji: 'enpitsu',   emoji: '✏️' },
  { letter: 'お', romaji: 'o',   phonetic: '/o/',   word: 'おに',       wordRomaji: 'oni',       emoji: '👹' },
  { letter: 'か', romaji: 'ka',  phonetic: '/ka/',  word: 'かさ',       wordRomaji: 'kasa',      emoji: '☂️' },
  { letter: 'き', romaji: 'ki',  phonetic: '/ki/',  word: 'きつね',     wordRomaji: 'kitsune',   emoji: '🦊' },
  { letter: 'く', romaji: 'ku',  phonetic: '/ku/',  word: 'くも',       wordRomaji: 'kumo',      emoji: '☁️' },
  { letter: 'け', romaji: 'ke',  phonetic: '/ke/',  word: 'けむり',     wordRomaji: 'kemuri',    emoji: '💨' },
  { letter: 'こ', romaji: 'ko',  phonetic: '/ko/',  word: 'こま',       wordRomaji: 'koma',      emoji: '🌀' },
  { letter: 'さ', romaji: 'sa',  phonetic: '/sa/',  word: 'さかな',     wordRomaji: 'sakana',    emoji: '🐟' },
  { letter: 'し', romaji: 'shi', phonetic: '/ɕi/',  word: 'しか',       wordRomaji: 'shika',     emoji: '🦌' },
  { letter: 'す', romaji: 'su',  phonetic: '/sɯ/',  word: 'すいか',     wordRomaji: 'suika',     emoji: '🍉' },
  { letter: 'せ', romaji: 'se',  phonetic: '/se/',  word: 'せみ',       wordRomaji: 'semi',      emoji: '🦗' },
  { letter: 'そ', romaji: 'so',  phonetic: '/so/',  word: 'そら',       wordRomaji: 'sora',      emoji: '🌤️' },
  { letter: 'た', romaji: 'ta',  phonetic: '/ta/',  word: 'たこ',       wordRomaji: 'tako',      emoji: '🐙' },
  { letter: 'ち', romaji: 'chi', phonetic: '/tɕi/', word: 'ちょうちょ', wordRomaji: 'chōcho',    emoji: '🦋' },
  { letter: 'つ', romaji: 'tsu', phonetic: '/tsɯ/', word: 'つき',       wordRomaji: 'tsuki',     emoji: '🌙' },
  { letter: 'て', romaji: 'te',  phonetic: '/te/',  word: 'てぶくろ',   wordRomaji: 'tebukuro',  emoji: '🧤' },
  { letter: 'と', romaji: 'to',  phonetic: '/to/',  word: 'とり',       wordRomaji: 'tori',      emoji: '🐦' },
  { letter: 'な', romaji: 'na',  phonetic: '/na/',  word: 'なし',       wordRomaji: 'nashi',     emoji: '🍐' },
  { letter: 'に', romaji: 'ni',  phonetic: '/ni/',  word: 'にじ',       wordRomaji: 'niji',      emoji: '🌈' },
  { letter: 'ぬ', romaji: 'nu',  phonetic: '/nɯ/',  word: 'ぬの',       wordRomaji: 'nuno',      emoji: '🧵' },
  { letter: 'ね', romaji: 'ne',  phonetic: '/ne/',  word: 'ねこ',       wordRomaji: 'neko',      emoji: '🐱' },
  { letter: 'の', romaji: 'no',  phonetic: '/no/',  word: 'のり',       wordRomaji: 'nori',      emoji: '🟫' },
  { letter: 'は', romaji: 'ha',  phonetic: '/ha/',  word: 'はな',       wordRomaji: 'hana',      emoji: '🌸' },
  { letter: 'ひ', romaji: 'hi',  phonetic: '/çi/',  word: 'ひつじ',     wordRomaji: 'hitsuji',   emoji: '🐑' },
  { letter: 'ふ', romaji: 'fu',  phonetic: '/ɸɯ/',  word: 'ふね',       wordRomaji: 'fune',      emoji: '⛵' },
  { letter: 'へ', romaji: 'he',  phonetic: '/he/',  word: 'へび',       wordRomaji: 'hebi',      emoji: '🐍' },
  { letter: 'ほ', romaji: 'ho',  phonetic: '/ho/',  word: 'ほし',       wordRomaji: 'hoshi',     emoji: '⭐' },
  { letter: 'ま', romaji: 'ma',  phonetic: '/ma/',  word: 'まめ',       wordRomaji: 'mame',      emoji: '🫘' },
  { letter: 'み', romaji: 'mi',  phonetic: '/mi/',  word: 'みかん',     wordRomaji: 'mikan',     emoji: '🍊' },
  { letter: 'む', romaji: 'mu',  phonetic: '/mɯ/',  word: 'むし',       wordRomaji: 'mushi',     emoji: '🐛' },
  { letter: 'め', romaji: 'me',  phonetic: '/me/',  word: 'めだか',     wordRomaji: 'medaka',    emoji: '🐠' },
  { letter: 'も', romaji: 'mo',  phonetic: '/mo/',  word: 'もも',       wordRomaji: 'momo',      emoji: '🍑' },
  { letter: 'や', romaji: 'ya',  phonetic: '/ja/',  word: 'やま',       wordRomaji: 'yama',      emoji: '🗻' },
  { letter: 'ゆ', romaji: 'yu',  phonetic: '/jɯ/',  word: 'ゆき',       wordRomaji: 'yuki',      emoji: '❄️' },
  { letter: 'よ', romaji: 'yo',  phonetic: '/jo/',  word: 'よる',       wordRomaji: 'yoru',      emoji: '🌃' },
  { letter: 'ら', romaji: 'ra',  phonetic: '/ra/',  word: 'らいおん',   wordRomaji: 'raion',     emoji: '🦁' },
  { letter: 'り', romaji: 'ri',  phonetic: '/ri/',  word: 'りんご',     wordRomaji: 'ringo',     emoji: '🍎' },
  { letter: 'る', romaji: 'ru',  phonetic: '/rɯ/',  word: 'るびー',     wordRomaji: 'rubī',      emoji: '💎' },
  { letter: 'れ', romaji: 're',  phonetic: '/re/',  word: 'れいぞうこ', wordRomaji: 'reizōko',   emoji: '🧊' },
  { letter: 'ろ', romaji: 'ro',  phonetic: '/ro/',  word: 'ろうそく',   wordRomaji: 'rōsoku',    emoji: '🕯️' },
  { letter: 'わ', romaji: 'wa',  phonetic: '/wa/',  word: 'わに',       wordRomaji: 'wani',      emoji: '🐊' },
  { letter: 'を', romaji: 'wo',  phonetic: '/o/',   word: '(particle)', wordRomaji: '',          emoji: '—' },
  { letter: 'ん', romaji: 'n',   phonetic: '/n/',   word: '(mid-word)', wordRomaji: '',          emoji: '—' },
];

export const KATAKANA = [
  { letter: 'ア', romaji: 'a',   phonetic: '/a/',   word: 'アイス',         wordRomaji: 'aisu',       emoji: '🍦' },
  { letter: 'イ', romaji: 'i',   phonetic: '/i/',   word: 'イルカ',         wordRomaji: 'iruka',      emoji: '🐬' },
  { letter: 'ウ', romaji: 'u',   phonetic: '/ɯ/',   word: 'ウサギ',         wordRomaji: 'usagi',      emoji: '🐰' },
  { letter: 'エ', romaji: 'e',   phonetic: '/e/',   word: 'エビ',           wordRomaji: 'ebi',        emoji: '🦐' },
  { letter: 'オ', romaji: 'o',   phonetic: '/o/',   word: 'オレンジ',       wordRomaji: 'orenji',     emoji: '🍊' },
  { letter: 'カ', romaji: 'ka',  phonetic: '/ka/',  word: 'カメラ',         wordRomaji: 'kamera',     emoji: '📷' },
  { letter: 'キ', romaji: 'ki',  phonetic: '/ki/',  word: 'キリン',         wordRomaji: 'kirin',      emoji: '🦒' },
  { letter: 'ク', romaji: 'ku',  phonetic: '/ku/',  word: 'クマ',           wordRomaji: 'kuma',       emoji: '🐻' },
  { letter: 'ケ', romaji: 'ke',  phonetic: '/ke/',  word: 'ケーキ',         wordRomaji: 'kēki',       emoji: '🎂' },
  { letter: 'コ', romaji: 'ko',  phonetic: '/ko/',  word: 'コアラ',         wordRomaji: 'koara',      emoji: '🐨' },
  { letter: 'サ', romaji: 'sa',  phonetic: '/sa/',  word: 'サメ',           wordRomaji: 'same',       emoji: '🦈' },
  { letter: 'シ', romaji: 'shi', phonetic: '/ɕi/',  word: 'シマウマ',       wordRomaji: 'shimauma',   emoji: '🦓' },
  { letter: 'ス', romaji: 'su',  phonetic: '/sɯ/',  word: 'スイカ',         wordRomaji: 'suika',      emoji: '🍉' },
  { letter: 'セ', romaji: 'se',  phonetic: '/se/',  word: 'セーター',       wordRomaji: 'sētā',       emoji: '🧥' },
  { letter: 'ソ', romaji: 'so',  phonetic: '/so/',  word: 'ソファ',         wordRomaji: 'sofa',       emoji: '🛋️' },
  { letter: 'タ', romaji: 'ta',  phonetic: '/ta/',  word: 'タコ',           wordRomaji: 'tako',       emoji: '🐙' },
  { letter: 'チ', romaji: 'chi', phonetic: '/tɕi/', word: 'チーズ',         wordRomaji: 'chīzu',      emoji: '🧀' },
  { letter: 'ツ', romaji: 'tsu', phonetic: '/tsɯ/', word: 'ツバメ',         wordRomaji: 'tsubame',    emoji: '🐦' },
  { letter: 'テ', romaji: 'te',  phonetic: '/te/',  word: 'テレビ',         wordRomaji: 'terebi',     emoji: '📺' },
  { letter: 'ト', romaji: 'to',  phonetic: '/to/',  word: 'トマト',         wordRomaji: 'tomato',     emoji: '🍅' },
  { letter: 'ナ', romaji: 'na',  phonetic: '/na/',  word: 'ナス',           wordRomaji: 'nasu',       emoji: '🍆' },
  { letter: 'ニ', romaji: 'ni',  phonetic: '/ni/',  word: 'ニワトリ',       wordRomaji: 'niwatori',   emoji: '🐔' },
  { letter: 'ヌ', romaji: 'nu',  phonetic: '/nɯ/',  word: 'ヌードル',       wordRomaji: 'nūdoru',     emoji: '🍜' },
  { letter: 'ネ', romaji: 'ne',  phonetic: '/ne/',  word: 'ネコ',           wordRomaji: 'neko',       emoji: '🐱' },
  { letter: 'ノ', romaji: 'no',  phonetic: '/no/',  word: 'ノート',         wordRomaji: 'nōto',       emoji: '📓' },
  { letter: 'ハ', romaji: 'ha',  phonetic: '/ha/',  word: 'ハト',           wordRomaji: 'hato',       emoji: '🕊️' },
  { letter: 'ヒ', romaji: 'hi',  phonetic: '/çi/',  word: 'ヒツジ',         wordRomaji: 'hitsuji',    emoji: '🐑' },
  { letter: 'フ', romaji: 'fu',  phonetic: '/ɸɯ/',  word: 'フラミンゴ',     wordRomaji: 'furamingo',  emoji: '🦩' },
  { letter: 'ヘ', romaji: 'he',  phonetic: '/he/',  word: 'ヘリコプター',   wordRomaji: 'herikoputā', emoji: '🚁' },
  { letter: 'ホ', romaji: 'ho',  phonetic: '/ho/',  word: 'ホタル',         wordRomaji: 'hotaru',     emoji: '✨' },
  { letter: 'マ', romaji: 'ma',  phonetic: '/ma/',  word: 'マンゴー',       wordRomaji: 'mangō',      emoji: '🥭' },
  { letter: 'ミ', romaji: 'mi',  phonetic: '/mi/',  word: 'ミツバチ',       wordRomaji: 'mitsubachi', emoji: '🐝' },
  { letter: 'ム', romaji: 'mu',  phonetic: '/mɯ/',  word: 'ムース',         wordRomaji: 'mūsu',       emoji: '🫎' },
  { letter: 'メ', romaji: 'me',  phonetic: '/me/',  word: 'メロン',         wordRomaji: 'meron',      emoji: '🍈' },
  { letter: 'モ', romaji: 'mo',  phonetic: '/mo/',  word: 'モモ',           wordRomaji: 'momo',       emoji: '🍑' },
  { letter: 'ヤ', romaji: 'ya',  phonetic: '/ja/',  word: 'ヤギ',           wordRomaji: 'yagi',       emoji: '🐐' },
  { letter: 'ユ', romaji: 'yu',  phonetic: '/jɯ/',  word: 'ユニコーン',     wordRomaji: 'yunikōn',    emoji: '🦄' },
  { letter: 'ヨ', romaji: 'yo',  phonetic: '/jo/',  word: 'ヨット',         wordRomaji: 'yotto',      emoji: '⛵' },
  { letter: 'ラ', romaji: 'ra',  phonetic: '/ra/',  word: 'ライオン',       wordRomaji: 'raion',      emoji: '🦁' },
  { letter: 'リ', romaji: 'ri',  phonetic: '/ri/',  word: 'リンゴ',         wordRomaji: 'ringo',      emoji: '🍎' },
  { letter: 'ル', romaji: 'ru',  phonetic: '/rɯ/',  word: 'ルビー',         wordRomaji: 'rubī',       emoji: '💎' },
  { letter: 'レ', romaji: 're',  phonetic: '/re/',  word: 'レモン',         wordRomaji: 'remon',      emoji: '🍋' },
  { letter: 'ロ', romaji: 'ro',  phonetic: '/ro/',  word: 'ロボット',       wordRomaji: 'robotto',    emoji: '🤖' },
  { letter: 'ワ', romaji: 'wa',  phonetic: '/wa/',  word: 'ワニ',           wordRomaji: 'wani',       emoji: '🐊' },
  { letter: 'ヲ', romaji: 'wo',  phonetic: '/o/',   word: '(particle)',     wordRomaji: '',           emoji: '—' },
  { letter: 'ン', romaji: 'n',   phonetic: '/n/',   word: '(mid-word)',     wordRomaji: '',           emoji: '—' },
];

// Pair modes:
//   'alphabet' — both Latin scripts; same letter, each language shows its own phonetic sound and word
//   'kana'     — both kana scripts; same sound shown in hiragana and katakana side by side
export const PAIRS = [
  { id: 'en-es', mode: 'alphabet', labelA: 'English',  labelB: 'Español',  colorA: '#6B8F71', colorB: '#C17B5A', scriptA: 'latin', scriptB: 'latin', dataA: ENGLISH,  dataB: SPANISH,  previewA: 'A', previewB: 'A' },
  { id: 'hi-ka', mode: 'kana',     labelA: 'ひらがな', labelB: 'カタカナ',  colorA: '#6B6FA8', colorB: '#5A5A9A', scriptA: 'kana',  scriptB: 'kana',  dataA: HIRAGANA, dataB: KATAKANA, previewA: 'あ', previewB: 'ア' },
];
